### ISSUE TITLE
My first issue

### ISSUE THREAD

**Issue by agui0091** [agui0091/mtm6201-week1#1]
@abhaysharma checking issues

**Comment by agui0091** [comment]
Teacher, I have problems taking the link to submit. Everything is in red color. Can you help me understand what happened?

**Comment by agui0091** [comment]
@abhaysharma Teacher, I have problems taking the link to submit. Everything is in red color. Can you help me understand what happened?

**Comment by abhaysharma** [comment]
@agui0091  I am not clear on the issue you are having, please attach a screenshot.
This is the link for submission https://agui0091.github.io/mtm6201-week1/

**Comment by agui0091** [comment]
@abhaysharma Teacher thanks so much for your answer. I already clarified my issue. have a good one!

**Comment by abhaysharma** [comment]
@agui0091 good! You may close the issue.
